### ISSUE TITLE
README incorrectly specifies default italic_style as asterisk

### ISSUE THREAD

**Issue by IllyaMoskvin** [thephpleague/html-to-markdown#111]
The ["Style options"](https://github.com/thephpleague/html-to-markdown/blob/c5b05d50c646d4e3cdfcc27b6d5ed62dfaeef4c1/README.md#style-options) section in the README states that:

> Bold and italic tags are converted using the asterisk syntax by default.

But as of [4.1.0](https://github.com/thephpleague/html-to-markdown/blob/c5b05d50c646d4e3cdfcc27b6d5ed62dfaeef4c1/CHANGELOG.md#410) (#58 and #59), italics are converted using underscore characters by default.

The README should be changed to reflect this development.

As an aside, I'm not sure that the phrasing "underlined syntax" is accurate. Wouldn't it be more accurate to call it "underscore syntax"? Sorry, not trying to be pedantic, just looking to avoid confusion with ["syntax for underline"](http://softwareengineering.stackexchange.com/questions/207727/why-there-is-no-markdown-for-underline). I'm not sure what the established terminology is in this case. I think the example makes it clear in either case.

**Comment by colinodell** [comment]
Good call!  If you'd like to submit a PR for that I'd happily merge it in :)
