### ISSUE TITLE
Lists not converting to *, but - instead

### ISSUE THREAD

**Issue by bkuhl** [thephpleague/html-to-markdown#135]
I think I must be missing a step.  

```php
$htmlConverter = new HtmlConverter();
$markdown = $htmlConverter->convert($html);
```

This HTML:

```html
<li>Item1</li><li>Item2</li><li>Item3</li>
```

Is converting to:

```
- Item1
- Item2
- Item3
```

I'm expecting it to come out as:

```
* Item1
* Item2
* Item3
```

Are my expectations correct or am I misunderstanding something?

**Comment by andreskrey** [comment]
Latest commonmark specs says that lists must start with a "bullet list marker" which can be -, + or *.

http://spec.commonmark.org/0.28/#list-items

So I guess html-to-markdown behaves as expected, but giving you less options. Maybe we should have a config param to set the marker type? Is that what you want?

**Comment by bkuhl** [comment]
Ah, common mark.  Wasn't aware that was a thing.  Yes, `*` is needed in my scenario.

**Comment by andreskrey** [comment]
You can instantiate your own ListConverter and use `*` instead of `-`

**Comment by colinodell** [comment]
> Maybe we should have a config param to set the marker type?

I think that's a great idea!

**Comment by manavo** [comment]
Will try and do this one

**Comment by bkuhl** [comment]
Wow, thanks
