### ISSUE TITLE
TravisCI builds are failing for PHP 5.3

### ISSUE THREAD

**Issue by manavo** [thephpleague/html-to-markdown#138]
Seems like you have to use Precise instead of Trusty.

https://github.com/travis-ci/travis-ci/issues/7163

**Comment by colinodell** [comment]
Fixed! https://travis-ci.org/thephpleague/html-to-markdown/jobs/285700637 :dolphin:

**Comment by manavo** [comment]
Ha, beat me to it :)

I'll close my PR then!
