### ISSUE TITLE
Improve test-suite

### ISSUE THREAD

**Issue by philsturgeon** [thephpleague/html-to-markdown#14]
It might be a good idea to improve the test-suite by looking at test data in projects like [Parsedown](https://github.com/erusev/parsedown/tree/master/test/data).

Some of the results from Parsedown might conflict with suggestions in #13 to use CommonMark, but thats because they aren't necessarily compliant with it themselves.

**Comment by colinodell** [comment]
We have significantly enhanced our test suite, including several edge cases noted by other projects.
