### ISSUE TITLE
Update project dependencies, namely PHPUnit

### ISSUE THREAD

**Issue by straube** [thephpleague/html-to-markdown#180]
The PHPUnit release used by the project is triggering a deprecation warning when running on PHP 7.2:

> PHP Deprecated:  The each() function is deprecated. This message will be suppressed on further calls in /Users/straube/Projects/html-to-markdown/vendor/phpunit/phpunit/src/Util/Getopt.php on line 38

From the [PHP manual](https://www.php.net/each):

> **Warning** This function has been *DEPRECATED* as of PHP 7.2.0. Relying on this function is highly discouraged.

I'm just not sure if we can both upgrade PHPUnit and keep the compatibility with older PHP versions, currently set to `>=5.3.3` on `composer.json`.

**Comment by colinodell** [comment]
This was fixed in PHPUnit 5.7, which only supports PHP 5.6+, so I'll widen the constraint to allow either PHPUnit 4 or 5 which should fix this.
