### ISSUE TITLE
markdown editor not working with mobile phone (android)

### ISSUE THREAD

**Issue by dominicdw** [thephpleague/html-to-markdown#182]
We are using the HTML to Markdown for the WordPress plugin and now the html-to-markdown not work with the mobile phone (android).

**Comment by colinodell** [comment]
Hey there,

This repository is a "vanilla" PHP library unrelated to WordPress - it does not include any WordPress plugin or other editor functionality.  It sounds like you might be using something like https://github.com/terrylinooo/githuber-md instead, so I'd recommend contacting them (or the appropriate plugin author) about your issue - they should be able to help you with that.
