### ISSUE TITLE
Force link style option

### ISSUE THREAD

**Issue by fveltmann** [thephpleague/html-to-markdown#187]
Would be great to have an option to force a link style. For example this: _\[link\]()_

So that even links where the descriptions and the URI are equal are parsed in this style and not like this: _\<link\>_

**Comment by colinodell** [comment]
I like that idea.  Perhaps call the option something like `use_autolinks` - if `true` (default), use `<...>` syntax where applicable; if `false`, always use the longer/full link syntax.

**Comment by digilist** [comment]
For links without any text it's also quite common to just write down the link without any "syntax". Most websites and tools transform it then automatically into a clickable link. I know this is not specified in the commonmark, but I would prefer such an option. Maybe also worth considering? :relaxed:

**Comment by Veltinator** [comment]
@colinodell Can you estimate when this feature will be implemented?

**Comment by colinodell** [comment]
I unfortunately don't have an ETA on this feature as my focus is primarily on league/commonmark 2.0 right now.  If anyone in the community would like to implement this feature and send a PR I will gladly review, merge, and release it!

**Comment by Tar-Minyatur** [comment]
Looked easy enough to do, so I gave it a shot (#188). Without concrete examples in here I'm not 100% sure I hit the spot though.

**Comment by colinodell** [comment]
This has been implemented and released in [4.10.0](https://github.com/thephpleague/html-to-markdown/releases/tag/4.10.0)! :tada:
