### ISSUE TITLE
Extraneous spaces added to beginnings of lines

### ISSUE THREAD

**Issue by strider72** [thephpleague/html-to-markdown#191]
When converting to markdown, if HTML is not contained in HTML elements, the script adds a single space to the start of every line beyond the first line.

Actual example (with text modified for anonymity.) (Yes, I know this is super primitive clunky HTML):
```
<b>Review Responsibilities:</b><br><br>

- Have iPad <i>and</i> charger in your possession<br><br>
- Periodically refresh page<br><br>
- Keep in touch<br><br>

<b>Designate and ensure alternate personnel are in place</b><br><br>
```

results in this:

```
**Review Responsibilities:**  
  
 - Have iPad *and* charger in your possession

 - Periodically refresh page

 - Keep in touch
  
 **Designate and ensure alternate personnel are in place**

```

Note the extraneous leading spaces on all text lines other than the first.

Technically I could just run a separate script to chop leading spaces off each line, except sometimes they're supposed to be there (e.g. indented lists), so no... I can't reliably do that without affecting the real contents

**Comment by strider72** [comment]
By "HTML is not contained in HTML elements" I mean that the overall text is not wrapped in <p> tags or whatnot.  It doesn't appear to happen if I wrap each bit in <p> tags.  But I can't assume this given my source data.

I did an experiment. I took the source HTML above, converted it to Markdown with this script, then used your Commonmark script to convert it back to HTML.

Here is the result:

**Review Responsibilities**:

  - Have iPad and charger in your possession
  - Periodically refresh page
  - Keep in touch
**Designate and ensure alternate personnel are in place**

The extraneous spaces result in the final sentence being pushed up into the last list item. The resulting HTML:
```
<p><strong>Review Responsibilities:</strong></p>
<ul>
<li>Have iPad <em>and</em> charger in your possession</li>
<li>Periodically refresh page</li>
<li>Keep in touch<br />
<strong>Designate and ensure alternate personnel are in place</strong>
</li>
</ul>
```

**Comment by svenhaveman** [comment]
Could you share some more info? I can't reproduce this. This is my testcode:

`require 'vendor/autoload.php';

use League\HTMLToMarkdown\HtmlConverter;

$converter = new HtmlConverter();

$html = "<b>Review Responsibilities:</b><br><br>

- Have iPad <i>and</i> charger in your possession<br><br>
- Periodically refresh page<br><br>
- Keep in touch<br><br>

<b>Designate and ensure alternate personnel are in place</b><br><br>";

$markdown = $converter->convert($html);

echo $markdown;`

Then it outputs the following:

`➜  html-to-markdown git:(master) ✗ php test.php
**Review Responsibilities:**  
  
- Have iPad *and* charger in your possession  
  
- Periodically refresh page  
  
- Keep in touch  
  
**Designate and ensure alternate personnel are in place**  
  %                                                                                                                                                                                                                                     ➜  html-to-markdown git:(master) ✗ 
`

I think it's working like expected.
