### ISSUE TITLE
Preserve links and other tags with class attributes

### ISSUE THREAD

**Issue by nickcernis** [thephpleague/html-to-markdown#20]
HTML To Markdown should probably not convert tags with class attributes to HTML by default, so that the conversion is not destructive.

The option to convert all tags regardless (stripping class attributes) should be available, but probably not on by default.

This will likely help WordPress plugins such as [Ghost](https://wordpress.org/plugins/ghost/) to convert HTML to Markdown more faithfully without stripping essential class names.

This HTML:

`<span class="span-class">Label: </span><a class="link-class" href="http://example.com">Link</a>`

...should probably result in this (identical code):

`<span class="span-class">Label: </span><a class="link-class" href="http://example.com">Link</a>`

...instead of this:

`<span class="span-class">Label: </span>[Link](http://example.com)`

**Comment by eukaryoticx** [comment]
Appreciated @nickcernis . Give a shout out if you need help with testing.

**Comment by karllhughes** [comment]
Because this would be a breaking change, I think the default should be to handle links with classes as they are today, but we should add an option to allow retention of class attributes in links.

I'm going to start a PR for this soon, but am open to discussion. I know this was an old conversation.
