### ISSUE TITLE
Link is not converted to MarkDown

### ISSUE THREAD

**Issue by towerberlin** [thephpleague/html-to-markdown#200]
`<a href="https://www.youtube.com/watch?v=bBxCH3QKTJA">https://www.youtube.com/watch?v=bBxCH3QKTJA</a>`

**Comment by towerberlin** [comment]
`echo $converter->convert('<a href="https://www.youtube.com/watch?v=bBxCH3QKTJA">https://www.youtube.com/watch?v=bBxCH3QKTJA</a>')`

`<https://www.youtube.com/watch?v=bBxCH3QKTJA>`

**Comment by colinodell** [comment]
Hi @towerberlin.

`<https://www.youtube.com/watch?v=bBxCH3QKTJA>` is a valid URL link in Markdown.  This shorthand version is called an "[autolink](https://spec.commonmark.org/0.29/#autolinks)" and is used whenever the `href` and link label are the same.

See https://babelmark.github.io/?text=%3Chttps%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DbBxCH3QKTJA%3E for an example of how different Markdown parsers handle this input.  (You'll see that virtually all of them produce the expected HTML output)

**Comment by towerberlin** [comment]
Ok and thanks for your answer
