### ISSUE TITLE
Convert HTML table to Markdown table

### ISSUE THREAD

**Issue by dsuurlant** [thephpleague/html-to-markdown#201]
As far as I can see, this converter does not handle HTML tables to convert them to Markdown (example: https://github.com/johnbeech/html-table-to-markdown-converter)

Example input:
```html
<table>
  <th>
    <td>Header 1</td>
    <td>Header 2</td>
    <td>Header 3</td>
  </th>
  <tr>
    <td>value 1</td>
    <td>value 2</td>
    <td>value 3</td>
  </tr>
</table>
```

Desired output (possibly with improved cell formatting):
```
|Header 1|Header 2|Header 3|
|---|---|---|
|value 1|value2|value3|
```

Is that a feature currently in development and/or to contribute to?

**Comment by markopy** [comment]
@dsuurlant Have you already started work on this? I need table support as well and will contribute it but prefer not to duplicate effort.
