### ISSUE TITLE
Do you support the reserved space parameter

### ISSUE THREAD

**Issue by ClearSeve** [thephpleague/html-to-markdown#234]
Want to &nbsp; keep as is

```
<code> &nbsp;</code>
```

Convert to

```
`&nbsp;`
```

Include other invisible characters

**Comment by colinodell** [comment]
Hi there!

To get your desired Markdown you'd need to have HTML like this:

```html
<code> &amp;nbsp;</code>
```

This is because `&nbsp;` in HTML is converted into a literal non-breaking space character, both in your browser and in this library.  See https://jsbin.com/fupupoyupe/edit?html,output for an example.
