### ISSUE TITLE
Cannot open HtmlConverter.php in Android Chrome to execute HTML to Markdown conversion process.

### ISSUE THREAD

**Issue by codenamedpkt** [thephpleague/html-to-markdown#237]
### Version(s) affected

all version in your repo, opened by Android Chrome with Android latest 5 major version.

### Description

Hi All,
I am currently download a web page and converting to markdown from url below with using your repo:

https://www.expertreviews.co.uk/technology/1415351/best-website-builders

When I downloaded your src folder in your repo and executing from Android Chrome, It cannot render php files and show converter UI.

### How to reproduce

Tried entering `file:///sdcard/path/to/repo`, `file://localhost/sdcard/path/to/repo`, `file:///storage/emulated/0/path/to/repo`, etc., in latest version of Android Chrome, with Extended Support of Android OS, even opening third party file manager we prefered and navigate the php file, running with Samsung Galaxy S9. 

### Possible solution

Your repo is no fixing needed. However, you have to try opening mentioned files in latest Android Chrome with latest 5 major supported version of Android OS, rendering them correctly. 
Another possible solution is create an GitHub page not only this repo, by using GitHub Actions, are also rendering supported with latest version Android Chrome, shows UI correctly and able downloading markdowns from HTML, with supported artifacts in your repos.

### Did this project help you today? Did it make you happy in any way?

Nope. We read issues in your repo. And walked around Stacks. No resolved solution exist in the web.

**Comment by colinodell** [comment]
This project must be run with a PHP interpreter which you'd typically install on a web server. You cannot run it with just a web browser.
