### ISSUE TITLE
Links do not render when href is same as the text

### ISSUE THREAD

**Issue by acmitch** [thephpleague/html-to-markdown#49]
```php
$test = '<a href="http://test.com/">http://test.com/</a>';

echo $markdown->convert($test);
```
**produces:**  `<http: test.com="">"<br><br><br><br></http:>`

However after changing the text it works.
```php
$test = '<a href="http://test.com/">test</a>';

echo $markdown->convert($test);
```
**produces:**  `[test](http://test.com/) `

If actually even works if you change one character (I took off the `/` in the text):
```php
$test = '<a href="http://test.com/">http://test.com</a>';

echo $markdown->convert($test);
```
**produces:**  `[http://test.com](http://test.com/)`

**Comment by acmitch** [comment]
Okay a little misleading, HtmlPurifiier is reading <http://test.com/> as an element and stripping it, sry for the noise. Great library by the way.

**Comment by Stolzenhain** [comment]
This is issue persits on our setup – judging from the last comment, HtmlPurifier only introduced the breaks but was not the root of the issue (wrong conversion of links w/ identical text).

~~~html
<a href="https://example.com">https://example.com</a>
~~~

produces

~~~markdown
<https://example.com>
~~~

It looks like Ticket #150 is related.

Would it be possible to reopen this ticket?

For now, the only solution is to search for angle brackets in the text and replace them with the correct markup or maintain little differences (like adding or removing a slash).

**Comment by colinodell** [comment]
> Edit: Ok, looking at the source this seems to be expected behaviour for explicit Markdown links. There's probably no way of turning that one off, right?

Correct, this is the [autolink functionality](https://spec.commonmark.org/0.29/#autolinks) which is part of the CommonMark spec.
