### ISSUE TITLE
&nbsp; before/after <a> tags are lost

### ISSUE THREAD

**Issue by lsproc** [thephpleague/html-to-markdown#53]
If you have, for some reason
```
    blah blah blah&nbsp;<a href="http://www.google.com">google</a>&nbsp;blah blah blah
```
the resultant output is in the format:
```
    blah blah blah[google](http://www.google.com)blah blah blah
```
the spaces either side of the link go missing.

This does not seem to happen when the space is a space character (" ") instead of ```&nbsp```;.

**Comment by colinodell** [comment]
I am unable to replicate this issue using the latest version (4.0.1):

![2015-09-13_11-02-31](https://cloud.githubusercontent.com/assets/202034/9837250/03688418-5a07-11e5-8b5b-74e28eaedcb5.png)

The resulting Markdown output preserves the space on both sides using the U+00A0 `NO-BREAK SPACE` character.

If you can provide a full code sample which displays this behavior, along with the version of PHP and this library used, I can certainly investigate further.  But as of now, everything seems to be okay.
