### ISSUE TITLE
Final rendering may strip content

### ISSUE THREAD

**Issue by marijnvdwerf** [thephpleague/html-to-markdown#63]
Since the convertor uses `DOMDocument` internally, output needs to be sanitised. This happens in [`HtmlConvertor::sanitize`](https://github.com/thephpleague/html-to-markdown/blob/941f89b80fa25679d0c1ab136da2928041f8143f/src/HtmlConverter.php#L183). Unfortunately, this step may also strip content, as is shown in the following example.

**Input**:
```html
<pre><code>...
&lt;script type = "text/javascript"&gt;
function startTimer() {
   var tim = window.setTimeout("hideMessage()", 5000)
}
</head>
<body>
...</pre></code>
```

**Actual**
```md
    ...
    <script type = "text/javascript">
    function startTimer() {
       var tim = window.setTimeout("hideMessage()", 5000)
    }
    
    
    ...
```

**Expected**
```md
    ...
    <script type = "text/javascript">
    function startTimer() {
       var tim = window.setTimeout("hideMessage()", 5000)
    }
    </head>
    </body>
    ...
```

**Comment by colinodell** [comment]
Fixed via #101
