### ISSUE TITLE
Paragraphs with empty-ish values are removed

### ISSUE THREAD

**Issue by marijnvdwerf** [thephpleague/html-to-markdown#66]
This happens because `empty()` considers `"0"` as being empty.

**Input**
```html
<p>0</p>
```

**Actual**:
```md

```

**Expected**:
```md
0
```

**Comment by andreskrey** [comment]
Might be late to the party but I couldn't reproduce this on version 4.2.1

**Comment by colinodell** [comment]
Thanks @andreskrey, I can confirm this issue no longer exists.
