### ISSUE TITLE
Non-autolinks should get escaped

### ISSUE THREAD

**Issue by marijnvdwerf** [thephpleague/html-to-markdown#68]
**Input**:

``` html
<p>&lt;league/commonmark&gt;, &lt;github.com/thephpleague&gt;, &lt;league@commonmark&gt;, &lt;https://github.com/thephpleague&gt;</p>
```

**Actual**:

``` md
<league/commonmark>, <github.com/thephpleague>,
 <league@commonmark>, <https://github.com/thephpleague>
```

**Expected**:

``` md
<league/commonmark>, <github.com/thephpleague>,
 \<league@commonmark>, \<https://github.com/thephpleague>
```

**Comment by colinodell** [comment]
I need to think about this one.  Any feedback for/against this would be appreciated.

**Comment by marijnvdwerf** [comment]
I've been using this library to convert legacy forum posts to Markdown ([example](http://www.onemorething.nl/community/topic/krijg-mails-continue-terug/#post-2797430)), but didn't want to change the final output. People wrote stuff in a certain way, and have seen it rendering like this.

It kinda depends what the goal of the project is. Identical rendered output, or a less exact approach.
