### ISSUE TITLE
Use an intermediate AST

### ISSUE THREAD

**Issue by colinodell** [thephpleague/html-to-markdown#72]
Some of the issues being reported are caused by (or related to) one of the following:
1. Converting HTML directly to a string
2. Not doing a great job of tracking element depth
3. Storing the resulting MD in the DOM tree

We'll need a major revamp of the codebase to address the issues that these things cause.  I therefore propose implementing an AST as an intermediate conversion step, similar to how league/commonmark works.

So basically as we traverse the DOM tree, we simultaneously build an AST which mirrors it (using the same Nodes and sub-classes from league/commonmark).  This part should be fairly straight-forward.  Once the AST is build, we pass that along to renderers which convert that AST representation into the final markdown.

In the long term, perhaps we could eventually merge the two codebases into a single library, which would be awesome!  (This wouldn't be done for at least two major versions though)

**Comment by brokentone** [comment]
Awesome! What is the path ahead on this? While I agree this is the *right* solution...

Many of the issues tagged right now are difficult to fix due to the potential to double process things. What if, in the Element recursor, an obnoxiously long and complex prefix is attached (to avoid it appearing in the text initially... ideally with a check as well) when a node is processed. This would be removed, then reappended on the return.

If we are able to switch on whether the node has ALREADY been processed will handle many of the current errors. Thoughts?

**Comment by colinodell** [comment]
Ideally I'd like to use the same AST we have in league/commonmark.  But before that can happen, I'd like to revisit that AST implementation and finalize things like:

 - Decoupling some of the parsing logic from node definitions
 - Implementing XML serialization
 - See whether user-defined node names and parent names work better than relying on PHP class and namespace names

Once that's finalize, the real work on this project can begin.  This will likely entail major changes to this codebase and how certain parsing functions work.  Some of the current parsing techniques and "workarounds" may no longer be used since we'll have a solid AST to work off of.

In the mean time, I'm okay with implementing bug fixes and certain workarounds to address current issues, knowing that they'll likely be unnecessary and thrown out in the future.

**Comment by brokentone** [comment]
Thanks for quick response! I may have a little time I can throw against this, as it is quite useful for a project I'm working on right now. If you can cut up some of the tasks, I'd be happy to pitch in. Happy to discuss offline as well.

**Comment by colinodell** [comment]
I've posted my thoughts to https://github.com/thephpleague/commonmark/issues/232.  These are just ideas I'd like to investigate - I've not made any decisions just yet.  Please feel free to review them, maybe try them out, and let me know your thoughts :)
