### ISSUE TITLE
Non-standard link conversion when link text is the link href

### ISSUE THREAD

**Issue by apostrophest** [thephpleague/html-to-markdown#82]
https://github.com/thephpleague/html-to-markdown/blob/master/src/Converter/LinkConverter.php#L22

I can't find any precedent for this syntax in any flavor of Markdown. This library can create invalid Markdown if the source HTML has a tag like <a href="http://abc.com/">http://abc.com/</a>.

This non-standard shorthand should be removed.

**Comment by colinodell** [comment]
These are called autolinks and they're supported by the CommonMark standard, which we're aiming to follow as much as possible: http://spec.commonmark.org/0.22/#autolinks

[According to these test results from Babelmark 2](http://johnmacfarlane.net/babelmark2/?normalize=1&text=%3Chttp%3A%2F%2Fwww.google.com%3E), 89% of the most-popular Markdown parsers support this syntax, as does GitHub, StackOverflow, Reddit, and others.

**Comment by apostrophest** [comment]
Thank you for the prompt reply and for your reasoning. I can understand adhering to CommonMark. I'll account for this in another way.

For reference, the particular issue I encountered was with Apple News. It does not support the autolink syntax. https://developer.apple.com/library/ios/documentation/General/Conceptual/Apple_News_Format_Ref/Markdown.html#//apple_ref/doc/uid/TP40015408-CH85-SW1

**Comment by alexking** [comment]
It would be nice if this didn't convert to an autolink if it doesn't meet the CommonMark definition. For example, right now `<a href="test">test</a>` will convert to `<test>`, even though CommonMark says that isn't a valid autolink.

**Comment by colinodell** [comment]
Agreed.  It should be too difficult to implement a regular expression to check the `href` and determine whether or not it conforms to [the CommonMark definition of an absolute URI](https://spec.commonmark.org/0.27/#absolute-uri): if so, use autolink.
