### ISSUE TITLE
Recursively decode entities

### ISSUE THREAD

**Issue by brokentone** [thephpleague/html-to-markdown#88]
Double encoding is a common error, but there is nothing preventing greater over encoding than 2x. When properly unencoded, `html_entity_decode ` will not affect the output, so could recursively run such a function until it comes back identical.

https://github.com/thephpleague/html-to-markdown/blob/master/src/HtmlConverter.php#L199-L200

**Comment by brokentone** [comment]
While my issue remains, my solution might not be so simple. Reading through the Gruber entity encoding spec, there likely are a lot of things out of spec right now. For example, the docs say:

>Similarly, because Markdown supports inline HTML, if you use angle brackets as delimiters for HTML tags, Markdown will treat them as such.
...
>However, inside Markdown code spans and blocks, angle brackets and ampersands are always encoded automatically. This makes it easy to use Markdown to write about HTML code.

```
$this->html_gives_markdown('<code>&lt;p&gt;Some sample HTML&lt;/p&gt;</code>', '`<p>Some sample HTML</p>`');
```
Should be:
```
$this->html_gives_markdown('<code>&lt;p&gt;Some sample HTML&lt;/p&gt;</code>', '`&lt;p&gt;Some sample HTML&lt;/p&gt;`');
```

**Comment by colinodell** [comment]
IMO that first example is the correct one.  We should strive for compatibility with the CommonMark spec wherever possible.  (This may be difficult in some cases until the AST in #72 is implemented, which is okay.)

Try running the Markdown output through [commonmark.js](http://spec.commonmark.org/dingus/?text=%60%3Cp%3ESome%20sample%20HTML%3C%2Fp%3E%60) to see what the HTML output would be.

**Comment by brokentone** [comment]
So.... if you're going for commonmark compatibility, neither option -- the single decode is actually the right answer. I'm thinking I can hang the recursive decoder off the class to allow you to decode more if you need to. PR on its way.
