### ISSUE TITLE
Del tags support

### ISSUE THREAD

**Issue by Ilya-Zhulin** [thephpleague/html-to-markdown#91]
Hello to all. 
How I can convert `<del>strikethrough text</del>` to `~~strikethrough text~~` with existing version of your Html-to-markdown component?

Thanks!

**Comment by colinodell** [comment]
Unfortunately we don't have any plans to support this tag as it's not part
of the Commonmark specification. There has been some discussion on
including it, but no official adoption yet:
http://talk.commonmark.org/t/strikeout-threw-out-strikethrough-strikes-out-throughout/820/48

If that changes we will certainly include it.

**Comment by Ilya-Zhulin** [comment]
OK, I understand that it's not native Markdown. To use it in League/Commonmark I programmed a plugin. Does Html-to-markdown support some plugins maybe?
For now I added it to source code and it works (I can make a pull request), but it's not correct in my opinion...
Thanks!

**Comment by colinodell** [comment]
Yep, simply create a new class which implements `ConverterInterface`.  It has two methods:

1. `getSupportedTags()` which should probably return `['del']`.
2. `convert(ElementInterface $element)` which converts the `<del>` HTML element into the resulting Markdown.
