### ISSUE TITLE
How can I use it without composer?

### ISSUE THREAD

**Issue by sajadshafizadeh** [thephpleague/html-to-markdown#95]
I'm trying to implement your library on local. I'm using xampp and I want to use your library to convert HTML to markdown. How can implement it?

**Comment by colinodell** [comment]
Although this library doesn't require any third-party libraries to run, it does use Composer's automatically-generated `vendor/autoload.php` script.

So, if you wanted to use this library without Composer, you'll need to manually implement PSR-4 autoloading and `require()` that before utilizing this library's code.
