### ISSUE TITLE
Is the markdown `GFM` style?

### ISSUE THREAD

**Issue by xaero7** [thephpleague/html-to-markdown#96]
Is the markdown `GFM` style?
the `<code class="php">`content does not hold with " \`\`\` " or  " \`\`\`php "

**Comment by colinodell** [comment]
This project does not (yet) adhere to any specific style.  Some GFM may work but we don't guarantee 100% compatibility.

The long-term goal is to eventually support CommonMark (#13, #27), with the possibility of having extensions for GFM.
